FROM php:apache

COPY index.php /var/www/html/index.php
COPY contact.php /var/www/html/contact.php
COPY about.php /var/www/html/about.php
COPY test.php /var/www/html/test.php
COPY flag.php /var/www/html/flag.php
COPY robots.txt /var/www/html/robots.txt
